### ISSUE TITLE
Support more environments that just staging, production, and independent

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-pack-k8s#17]
Currently, the goal environment for a KubernetesDeploy is limited to "production", which gets converted to ProductionEnvironment, "testing", which gets converted to StagingEnvironment, and anything else gets converted to "IndependencOfEnvironment". This does not really capture many common scenarios. Determine some way to support more environments that does not break the general categorization of goals by environment.

/cc @cdupuis

**Comment by cdupuis** [comment]
Yeah, I've seen that too in one of the SDMs I recently worked on: https://github.com/atomisthq/xxx-sdm/blob/master/lib/machine/goals.ts#L57
