### ISSUE TITLE
Support Kubernetes credential helpers

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-pack-k8s#25]
Currently only in-cluster and kubeconfig with static credential authentication is supported. Add support for using credentials helpers like those used by EKS and GKE.

**Comment by AdilusPrimus** [comment]
EKS Use case:
Id did set the KUBECONFIG variable pointing on my ~/.kube/config and I did define as well an ENV variable called AWS_PROFILE pointing on ~/.aws/credentials.
It does recognize as seen in the logs, the right Kubernetes server as currently configured locally on my system:
{"url":"https://7XXXX00E61.sk1.us-east-1.eks.amazonaws.com","version":"v1beta1","path":"/apis/apps/v1beta1","http":{"requestOptions":{"baseUrl":"https://XXXX0E61.sk1.us-east-1.eks.amazonaws.com",
but it doesn't seem to be able to use the auth helpers as discussed with @ddgenome here.
I'll try to adapt the scripts as documented in the following example of the js k8s library integrated in the atomist k8s plugin:
https://github.com/godaddy/kubernetes-client/blob/master/examples/iam-auth.js
Thanks @ddgenome for your time!
