### ISSUE TITLE
Support Custom Goal descriptions

### ISSUE THREAD

**Issue by ipcrm** [atomist/sdm-pack-k8s#54]
Currently custom goal descriptions for complete are overwritten by the pack and always updated to `Deployed <cluster>:<ns>/<deploymentName>`.  Would like the ability to define custom descriptions and have them preserved.

**Comment by ddgenome** [comment]
This commit https://github.com/atomist/sdm-pack-k8s/commit/949b5836c611f888e8664fc69e5b833354bd36e1 improved the quality of the information displayed by default, but allowing for custom goal descriptions may still be useful. An alternative would be for user's desiring custom goal descriptions to extend the KubernetesDeploy class.
