### ISSUE TITLE
Improve information in errors of retry failures

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-pack-k8s#75]
Because the object thrown from the kubernetes client/request library is non-standard, i.e., does not have a `message: string` property, the returned error messages from, for example, deploy failures are not as informative as they could be. Try to capture more useful information from the final error thrown.

**Comment by ddgenome** [comment]
@cdupuis do you still have the example of this? I looked at the code at Kubernetes API retries are done using `logRetry()` which uses the `errMsg()` function to try to find a reasonable error message, including in `e.body.message` and `e.response.body.message`.

**Comment by cdupuis** [comment]
This code worked for me:

```
    await logRetry(async () => {
        try {
            return await req.clients.apps.patchNamespacedDeployment(req.name, req.ns, spec);
        } catch (e) {
            throw new Error(e.response.body.message);
        }
    }, `patch deployment ${slug}`);
```

**Comment by ddgenome** [comment]
Something must be intercepting the thrown error before `logRetry`/`errMsg` is able to process it.

**Comment by cdupuis** [comment]
It is this part that is causing issues:
```
try {
			resolve(await input(attemptNumber));
		} catch (error) {
			if (!(error instanceof Error)) {
				reject(new TypeError(`Non-error was thrown: "${error}". You should only throw errors.`));
				return;
			}
```

**Comment by ddgenome** [comment]
`doWithRetry` wouldn't work because there is no `e.message` on errors from the Kubernetes client library, although it looks like that will be changing:

-   https://github.com/kubernetes-client/javascript/issues/336
-   https://github.com/OpenAPITools/openapi-generator/issues/3872
-   https://github.com/OpenAPITools/openapi-generator/pull/3876

Until those changes make their way into a release, I'll work around it in `logRetry`.
