### ISSUE TITLE
EncryptSecret function ignores stringData

### ISSUE THREAD

**Issue by timothysparg** [atomist/sdm-pack-k8s#78]
The [Kubernetes secrets page](https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually) has the following line:

> The Secret contains two maps: data and stringData. The data field is used to store arbitrary data, encoded using base64. The stringData field is provided for convenience, and allows you to provide secret data as unencoded strings.

but if I encrypt a secret then the stringData section remains unchanged.

see example below:
<img src="https://user-images.githubusercontent.com/6872586/66913344-be0c4c80-f014-11e9-9c6d-8a34c0b27434.png" width="500">

If I read the section properly, the following should be expected
- `stringData` should be encrypted and moved into the `data` section
- If a field exists in the `data` and `stringData` then the value from the `stringData` field should be used

**Comment by ddgenome** [comment]
Good catch.

When you say, "`stringData` should be encrypted and moved into the `data` section", do you mean "`stringData` should be _encoded_ and moved into the `data` section"?

**Comment by timothysparg** [comment]
I think the answer is `encoded `and then `encrypted`. At least that's my reading of this section:

> For certain scenarios, you may wish to use the stringData field instead. This field allows you to put a non-base64 encoded string directly into the Secret, and the string will be encoded for you when the Secret is created or updated.

**Comment by ddgenome** [comment]
That makes sense to me. Basically, we should support `stringData` since we currently do not.
